server:
  port: ${portMSCifras}
spring:
  data:
    mongodb:
      authentication-database: ${authenticationdatabaseMongo}
      username: ${usrMongoCifras} 
      password: ${pwMongoCifras}
      database: ${databaseMongo}
      port: ${portMongo}
      host: ${hostMongo}
logging:
  file: ${fileLogCifras}
  level:
    root: INFO
    org.springframework.web: INFO
    com.demo: INFO
    org.hibernate: INFO